import { chromium } from 'playwright';
const browser = await chromium.launch({ channel: 'chrome' }).catch(() => chromium.launch());
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto('http://localhost:4200', { waitUntil: 'networkidle' });
await page.waitForTimeout(2500);
await page.click('.header__theme');
await page.waitForTimeout(800);
await page.screenshot({ path: 'dk2-dark-landing.png' });
await page.goto('http://localhost:4200/login');
await page.fill('#email', 'altro@spintabelle.it');
await page.fill('#password', 'password123');
await page.click('button[type=submit]');
await page.waitForURL('http://localhost:4200/');
await page.goto('http://localhost:4200/lezioni');
await page.waitForSelector('.lesson-card', { timeout: 15000 });
await page.waitForTimeout(1200);
await page.screenshot({ path: 'dk4-dark-lezioni.png' });
console.log('[e2e] lezioni in dark OK, card:', await page.locator('.lesson-card').count());
// guard admin da utente normale in dark
await page.goto('http://localhost:4200/admin');
await page.waitForURL('http://localhost:4200/');
console.log('[e2e] roleGuard redirect OK');
await browser.close();
